name: 'Check All CI Completion'
description: 'wether all ci status which be related to commit are success or not'
inputs:
  ignore_check_suite_ids:
    description: 'the ignore check_suite_ids for specific git commit. ex) 1111,2222'
    required: true
outputs:
  result:
    description: 'the RESULT of the specific check-suites (success or fail)'
    value: ${{ steps.check-ci-statuses.outputs.result }}
  status:
    description: 'the STATUS of the specific check-suites (completed or in-progress)'
    value: ${{ steps.check-ci-statuses.outputs.status }}

runs:
  using: "composite"
  steps:
    - id: check-ci-statuses
      shell: bash
      env:
        IGNORE_CHECK_SUITE_IDS: "${{ inputs.ignore_check_suite_ids }}"
      run: |

        set -x

        # get this job's check suite id, because of ignore this job
        echo "${{ github.token }}" | gh auth login --with-token

        # get all ci check-suites status
        # https://docs.github.com/ja/rest/reference/checks#get-a-check-suite
        STATUS=$(gh api "repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}/check-suites" \
          | jq -r ".check_suites[] \
          | select(any(.app;.slug != \"codecov\")) \
          | select(any(.app;.slug != \"dependabot\")) \
          | select(any(.app;.slug != \"renovate\")) \
          | select([.id] | inside([${IGNORE_CHECK_SUITE_IDS:-dummy_id}]) | not ) \
          | .status" \
          | sort \
          | uniq)

        [[ "${STATUS}" = "completed" ]] || STATUS="in-progress"
        echo "::set-output name=status::${STATUS}"

        # if all check-suites results are success or neutral, this ci is success
        # https://docs.github.com/ja/rest/guides/getting-started-with-the-checks-api#about-check-suites
        gh api "repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}/check-suites" \
            | jq -r ".check_suites[] \
                | select(any(.app;.slug != \"codecov\")) \
                | select(any(.app;.slug != \"dependabot\")) \
                | select(any(.app;.slug != \"renovate\")) \
                | select([.id] | inside([${IGNORE_CHECK_SUITE_IDS:-dummy_id}]) | not ) \
                | .conclusion" \
            | sort \
            | uniq \
            | grep -v -E "(success|neutral)" && RESULT="success" || RESULT="fail"

        echo "::set-output name=result::${RESULT}"
