name: 'Check All CI Completion'
description: 'wether all ci status which be related to commit are success or not'
inputs:
  commit-hash:
    description: 'git commit hash to get check suites'
    required: false
  disable-errexit:
    description: 'if true, use exit 0 whether CI results are not completed or not success'
    required: false
    default: 'false'
  ignore-check-suite-ids:
    description: 'ignore check_suite_ids'
    required: false
    default: '000000000000000'
  loop-count:
    description: 'How many loop in this ci'
    required: false
    default: '-1'
  timeout-seconds:
    description: 'How long run this ci'
    required: false
    default: '1800'
  sleep-seconds:
    description: 'Sleep seconds in a loop'
    required: false
    default: '30'
outputs:
  result:
    description: 'the RESULT of the specific check-suites (success or fail)'
    value: ${{ steps.check-ci-statuses.outputs.result }}
  status:
    description: 'the STATUS of the specific check-suites (completed or in-progress)'
    value: ${{ steps.check-ci-statuses.outputs.status }}

runs:
  using: "composite"
  steps:
    - id: check-ci-statuses
      shell: bash
      env:
        DISABLE_ERREXIT: "${{ inputs.disable-errexit }}"
        IGNORE_CHECK_SUITE_IDS: "${{ inputs.ignore-check-suite-ids }}"
        LOOP_COUNT: "${{ inputs.loop-count }}"
        SLEEP_SECONDS: "${{ inputs.sleep-seconds }}"
        SPECIFIC_COMMIT_HASH: "${{ inputs.commit-hash }}"
        TIMEOUT_SECONDS: "${{ inputs.timeout-seconds }}"
      run: source ${{ github.action_path }}/action.sh
